//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _230801347.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MyWSSoap")]
    public interface MyWSSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        _230801347.ServiceReference1.HelloWorldResponse HelloWorld(_230801347.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<_230801347.ServiceReference1.HelloWorldResponse> HelloWorldAsync(_230801347.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name tname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loop", ReplyAction="*")]
        _230801347.ServiceReference1.loopResponse loop(_230801347.ServiceReference1.loopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/loop", ReplyAction="*")]
        System.Threading.Tasks.Task<_230801347.ServiceReference1.loopResponse> loopAsync(_230801347.ServiceReference1.loopRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public _230801347.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_230801347.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public _230801347.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_230801347.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loop", Namespace="http://tempuri.org/", Order=0)]
        public _230801347.ServiceReference1.loopRequestBody Body;
        
        public loopRequest() {
        }
        
        public loopRequest(_230801347.ServiceReference1.loopRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loopRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        public loopRequestBody() {
        }
        
        public loopRequestBody(string tname, string data) {
            this.tname = tname;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loopResponse", Namespace="http://tempuri.org/", Order=0)]
        public _230801347.ServiceReference1.loopResponseBody Body;
        
        public loopResponse() {
        }
        
        public loopResponse(_230801347.ServiceReference1.loopResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loopResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loopResult;
        
        public loopResponseBody() {
        }
        
        public loopResponseBody(string loopResult) {
            this.loopResult = loopResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWSSoapChannel : _230801347.ServiceReference1.MyWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWSSoapClient : System.ServiceModel.ClientBase<_230801347.ServiceReference1.MyWSSoap>, _230801347.ServiceReference1.MyWSSoap {
        
        public MyWSSoapClient() {
        }
        
        public MyWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _230801347.ServiceReference1.HelloWorldResponse _230801347.ServiceReference1.MyWSSoap.HelloWorld(_230801347.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _230801347.ServiceReference1.HelloWorldRequest inValue = new _230801347.ServiceReference1.HelloWorldRequest();
            inValue.Body = new _230801347.ServiceReference1.HelloWorldRequestBody();
            _230801347.ServiceReference1.HelloWorldResponse retVal = ((_230801347.ServiceReference1.MyWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_230801347.ServiceReference1.HelloWorldResponse> _230801347.ServiceReference1.MyWSSoap.HelloWorldAsync(_230801347.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<_230801347.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            _230801347.ServiceReference1.HelloWorldRequest inValue = new _230801347.ServiceReference1.HelloWorldRequest();
            inValue.Body = new _230801347.ServiceReference1.HelloWorldRequestBody();
            return ((_230801347.ServiceReference1.MyWSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _230801347.ServiceReference1.loopResponse _230801347.ServiceReference1.MyWSSoap.loop(_230801347.ServiceReference1.loopRequest request) {
            return base.Channel.loop(request);
        }
        
        public string loop(string tname, string data) {
            _230801347.ServiceReference1.loopRequest inValue = new _230801347.ServiceReference1.loopRequest();
            inValue.Body = new _230801347.ServiceReference1.loopRequestBody();
            inValue.Body.tname = tname;
            inValue.Body.data = data;
            _230801347.ServiceReference1.loopResponse retVal = ((_230801347.ServiceReference1.MyWSSoap)(this)).loop(inValue);
            return retVal.Body.loopResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_230801347.ServiceReference1.loopResponse> _230801347.ServiceReference1.MyWSSoap.loopAsync(_230801347.ServiceReference1.loopRequest request) {
            return base.Channel.loopAsync(request);
        }
        
        public System.Threading.Tasks.Task<_230801347.ServiceReference1.loopResponse> loopAsync(string tname, string data) {
            _230801347.ServiceReference1.loopRequest inValue = new _230801347.ServiceReference1.loopRequest();
            inValue.Body = new _230801347.ServiceReference1.loopRequestBody();
            inValue.Body.tname = tname;
            inValue.Body.data = data;
            return ((_230801347.ServiceReference1.MyWSSoap)(this)).loopAsync(inValue);
        }
    }
}
